### ISSUE TITLE
Upload Progress Bar doesn't work!

### ISSUE THREAD

**Issue by mrgrayhat** [codehaks/DropBox#1]
hi @codehaks ,
Upload Progress Bar And send Progress doesn't work(upload progress signalR).
I checked other branches, the percentage of upload progress does not change
Can you check this out?

https://github.com/codehaks/DropBox/blob/a0ff240b886423ffa78ff3e72d51b406e962e6e4/DropBox/Views/Home/Upload.cshtml#L42

With Regard.

**Comment by codehaks** [comment]
Tested again, It works perfectly on chrome
